budget: 100
squad_size: 15
max_per_team: 3
formations:
- - 3
  - 4
  - 3
- - 3
  - 5
  - 2
- - 4
  - 4
  - 2
horizon: 1
transfer_limit: 1
transfer_cost: 4
chip_rules:
  wildcard: true
  bench_boost: true
  triple_captain: true
  free_hit: true
cache_hours: 6
expected_points_model: fpl_ep_next
data_dir: ./data
output_dir: ./output
logging:
  level: INFO
  file: fpl_optimizer.log
solver:
  backend: pulp
  time_limit: 60
